import { send, badRequest, unauthenticated, forbidden, notFound, conflict, gone, normalizeTs } from '../http.js';
import { verifyPassword, hashPassword, issueAccessToken, newRefreshToken, hashRefreshToken, newInviteToken, hashInviteToken } from '../auth.js';
import { newId, nowIso } from '../db.js';
import { assertCan, resolve, resolveDevices, assertCanStartSession, assertMayGrant } from '../permissions.js';
import { assertRoleExists, assertCanModify, assertNotLastOwner, endActiveSessions, snapshotAuthority, sessionExpiry } from '../lifecycle.js';
import { audit } from '../audit.js';

const ok=(res,b,s=200)=>send(res,s,b);
const orgOf=(db,id)=>db.prepare('SELECT * FROM organizations WHERE id=? AND deleted_at IS NULL').get(id);
const active=(db,org,user)=>db.prepare("SELECT * FROM memberships WHERE org_id=? AND user_id=? AND status='active'").get(org,user);
const token=(m,secret)=>issueAccessToken({userId:m.user_id,orgId:m.org_id,role:m.role,permVersion:m.perm_version},secret);
const requireOrg=(db,ctx,id)=>{if(!orgOf(db,id)||ctx.orgId!==id)throw notFound();};
const pagination=(q)=>{const l=Number(q.get('limit')??100),o=Number(q.get('offset')??0);if(!Number.isInteger(l)||l<1||l>1000||!Number.isInteger(o)||o<0)throw badRequest('invalid pagination');return[l,o];};

export function registerRoutes(router,{db,secret}) {
  router.post('/v1/auth/login',async(c,_p,res)=>{const {email,password,orgId}=c.body;if(!email||!password)throw badRequest('email and password are required');const u=db.prepare('SELECT * FROM users WHERE email=? COLLATE NOCASE').get(String(email).toLowerCase());if(!u||!verifyPassword(password,u.password_hash))throw unauthenticated('invalid credentials');const ms=db.prepare("SELECT m.*,o.name,o.theme FROM memberships m JOIN organizations o ON o.id=m.org_id WHERE m.user_id=? AND m.status='active' AND o.deleted_at IS NULL ORDER BY m.created_at").all(u.id);const m=ms.find(x=>x.org_id===orgId)||ms[0];if(!m)throw unauthenticated('no active organization');const raw=newRefreshToken();db.prepare('INSERT INTO refresh_tokens (id,user_id,token_hash,family_id,expires_at) VALUES (?,?,?,?,?)').run(newId('rt'),u.id,hashRefreshToken(raw),newId('fam'),new Date(Date.now()+2592e6).toISOString());res.setHeader('set-cookie',`rt=${raw}; HttpOnly; SameSite=Strict;${process.env.COOKIE_SECURE === 'false' ? '' : ' Secure;'} Path=/`);ok(res,{token:token(m,secret),role:m.role,permissions:resolve(db,{userId:u.id,orgId:m.org_id}).permissions,user:{id:u.id,name:u.name,email:u.email},orgs:ms.map(x=>({id:x.org_id,name:x.name,theme:x.theme,role:x.role}))});});
  router.post('/v1/auth/refresh',async(c,_p,res)=>{const raw=(c.req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('rt='))?.slice(3);if(!raw)throw unauthenticated();const r=db.prepare("SELECT * FROM refresh_tokens WHERE token_hash=? AND revoked_at IS NULL AND expires_at>? ").get(hashRefreshToken(raw),nowIso());if(!r)throw unauthenticated();const m=db.prepare("SELECT * FROM memberships WHERE user_id=? AND status='active' ORDER BY created_at").get(r.user_id);if(!m)throw unauthenticated();ok(res,{token:token(m,secret)});});
  router.post('/v1/auth/token',async(c,_p,res)=>{const m=active(db,c.body.orgId,c.userId);if(!m)throw notFound();ok(res,{token:token(m,secret),role:m.role});});
  router.post('/v1/orgs',async(c,_p,res)=>{if(!c.body.name)throw badRequest('name is required');const id=newId('org'),theme=['cobalt','amber','violet','mint'][Math.floor(Math.random()*4)];db.transaction(()=>{db.prepare('INSERT INTO organizations (id,name,theme) VALUES (?,?,?)').run(id,c.body.name,theme);db.prepare("INSERT INTO memberships (id,org_id,user_id,role,status,joined_at) VALUES (?,?,?,'owner','active',?)").run(newId('mem'),id,c.userId,nowIso())})();const m=active(db,id,c.userId);ok(res,{id,name:c.body.name,theme,role:'owner',token:token(m,secret)});});
  router.get('/v1/orgs/:org/devices',async(c,p,res)=>{requireOrg(db,c,p.org);assertCan(db,c,'device:list');const ds=db.prepare('SELECT * FROM devices WHERE org_id=? AND deleted_at IS NULL ORDER BY name').all(p.org),ps=resolveDevices(db,{userId:c.userId,orgId:p.org,deviceIds:ds.map(x=>x.id)}).byDevice;ok(res,{devices:ds.filter(d=>ps[d.id]['device:view']?.effect==='allow').map(d=>({...d,permissions:ps[d.id]}))});});
  router.get('/v1/orgs/:org/members',async(c,p,res)=>{requireOrg(db,c,p.org);assertCan(db,c,'user:read');ok(res,{members:db.prepare("SELECT u.id AS user_id,u.name,u.email,m.role,m.status FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.org_id=? AND m.status!='removed' ORDER BY u.name").all(p.org)});});
  router.patch('/v1/orgs/:org/members/:userId',async(c,p,res)=>{requireOrg(db,c,p.org);assertCan(db,c,'user:role:update');if(p.userId===c.userId)throw Object.assign(forbidden(),{code:'SELF_ROLE_CHANGE'});const m=db.prepare('SELECT * FROM memberships WHERE org_id=? AND user_id=?').get(p.org,p.userId);if(!m)throw notFound();assertRoleExists(db,c.body.role);assertCanModify(db,c.role,m.role);assertCanModify(db,c.role,c.body.role);if(m.role==='owner'&&c.body.role!=='owner')assertNotLastOwner(db,p.org,p.userId);db.prepare('UPDATE memberships SET role=?,perm_version=perm_version+1 WHERE org_id=? AND user_id=?').run(c.body.role,p.org,p.userId);ok(res,{userId:p.userId,role:c.body.role});});
  router.post('/v1/orgs/:org/members/:userId/suspend',async(c,p,res)=>{requireOrg(db,c,p.org);assertCan(db,c,'user:remove');const m=db.prepare('SELECT * FROM memberships WHERE org_id=? AND user_id=?').get(p.org,p.userId);if(!m)throw notFound();assertCanModify(db,c.role,m.role);if(m.role==='owner')assertNotLastOwner(db,p.org,p.userId);db.transaction(()=>{db.prepare("UPDATE memberships SET status='suspended',perm_version=perm_version+1 WHERE org_id=? AND user_id=?").run(p.org,p.userId);endActiveSessions(db,{orgId:p.org,userId:p.userId,reason:'user_suspended'});})();ok(res,{status:'suspended'});});
  router.delete('/v1/orgs/:org/members/:userId/suspend',async(c,p,res)=>{requireOrg(db,c,p.org);assertCan(db,c,'user:remove');db.prepare("UPDATE memberships SET status='active',perm_version=perm_version+1 WHERE org_id=? AND user_id=?").run(p.org,p.userId);ok(res,{status:'active'});});
  router.delete('/v1/orgs/:org/members/me',async(c,p,res)=>{requireOrg(db,c,p.org);assertNotLastOwner(db,p.org,c.userId);db.transaction(()=>{db.prepare("UPDATE memberships SET status='removed',perm_version=perm_version+1 WHERE org_id=? AND user_id=?").run(p.org,c.userId);endActiveSessions(db,{orgId:p.org,userId:c.userId,reason:'membership_removed'});})();ok(res,{removed:true});});
  router.post('/v1/orgs/:org/invites',async(c,p,res)=>{requireOrg(db,c,p.org);assertCan(db,c,'user:invite');const {email,role}=c.body;if(!email||!role)throw badRequest('email and role are required');assertRoleExists(db,role);const raw=newInviteToken();try{db.prepare('INSERT INTO invites (id,org_id,email,role,token_hash,invited_by,expires_at) VALUES (?,?,?,?,?,?,?)').run(newId('inv'),p.org,email.toLowerCase(),role,hashInviteToken(raw),c.userId,new Date(Date.now()+6048e5).toISOString())}catch(e){if(String(e.message).includes('one_live_invite'))throw conflict('invite already exists');throw e}ok(res,{inviteToken:raw,email:email.toLowerCase(),role},201);});
  router.get('/v1/invites/:token',async(c,p,res)=>{const i=db.prepare('SELECT i.role,i.email,o.name AS org_name FROM invites i JOIN organizations o ON o.id=i.org_id WHERE i.token_hash=? AND i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at>?').get(hashInviteToken(p.token),nowIso());if(!i)throw notFound();ok(res,{orgName:i.org_name,email:i.email,role:i.role});});
  router.post('/v1/invites/:token/accept',async(c,p,res)=>{const i=db.prepare('SELECT * FROM invites WHERE token_hash=?').get(hashInviteToken(p.token));if(!i)throw notFound();if(i.accepted_at||i.revoked_at)throw conflict('invite has already been used','INVITE_USED');if(i.expires_at<=nowIso())throw gone();if(!c.body.name||!c.body.password)throw badRequest('name and password are required');const id=newId('usr');db.transaction(()=>{db.prepare('INSERT INTO users (id,email,name,password_hash) VALUES (?,?,?,?)').run(id,i.email,c.body.name,hashPassword(c.body.password));db.prepare('INSERT INTO memberships (id,org_id,user_id,role,status,joined_at) VALUES (?,?,?,?,?,?)').run(newId('mem'),i.org_id,id,i.role,'active',nowIso());db.prepare('UPDATE invites SET accepted_at=?,accepted_by=? WHERE id=?').run(nowIso(),id,i.id)})();const m=active(db,i.org_id,id);ok(res,{token:token(m,secret),role:i.role,email:i.email});});
  router.get('/v1/orgs/:org/grants',async(c,p,res)=>{requireOrg(db,c,p.org);assertCan(db,c,'user:read');ok(res,{grants:db.prepare('SELECT g.*,group_concat(gp.permission) AS permissions FROM grants g JOIN grant_permissions gp ON gp.grant_id=g.id WHERE g.org_id=? AND g.revoked_at IS NULL GROUP BY g.id ORDER BY g.created_at').all(p.org)});});
  router.post('/v1/orgs/:org/grants',async(c,p,res)=>{requireOrg(db,c,p.org);assertCan(db,c,'grant:create');const {userId,effect,permissions,deviceId,startsAt,expiresAt}=c.body;if(!userId||!['allow','deny'].includes(effect)||!Array.isArray(permissions)||!permissions.length)throw badRequest('invalid grant','unknown_permission');if(userId===c.userId)throw forbidden('cannot grant to yourself','self_grant');assertMayGrant(db,{...c,targetUserId:userId},permissions,deviceId??null);const id=newId('grt');db.transaction(()=>{db.prepare('INSERT INTO grants (id,org_id,user_id,device_id,effect,starts_at,expires_at,created_by) VALUES (?,?,?,?,?,?,?,?)').run(id,p.org,userId,deviceId??null,effect,normalizeTs(startsAt,'startsAt'),normalizeTs(expiresAt,'expiresAt'),c.userId);for(const x of permissions)db.prepare('INSERT INTO grant_permissions (grant_id,permission) VALUES (?,?)').run(id,x);audit(db,{orgId:p.org,actorId:c.userId,action:'grant.create',targetType:'grant',targetId:id,result:'allow',requestId:c.requestId});})();ok(res,{id},201);});
  router.delete('/v1/orgs/:org/grants/:grantId',async(c,p,res)=>{requireOrg(db,c,p.org);assertCan(db,c,'grant:revoke');db.prepare('UPDATE grants SET revoked_at=? WHERE id=? AND org_id=?').run(nowIso(),p.grantId,p.org);ok(res,{revoked:true});});
  router.post('/v1/orgs/:org/sessions',async(c,p,res)=>{requireOrg(db,c,p.org);const {deviceId,mode}=c.body;if(!['view','control','terminal'].includes(mode))throw badRequest('invalid mode');if(!db.prepare('SELECT 1 FROM devices WHERE id=? AND org_id=? AND deleted_at IS NULL').get(deviceId,p.org))throw notFound();assertCanStartSession(db,c,mode,deviceId);const id=newId('ses');try{db.prepare('INSERT INTO sessions (id,org_id,user_id,device_id,mode,state,authorized_by,expires_at) VALUES (?,?,?,?,?,?,?,?)').run(id,p.org,c.userId,deviceId,mode,'active',JSON.stringify(snapshotAuthority(db,{userId:c.userId,orgId:p.org,deviceId})),sessionExpiry(db,p.org))}catch(e){if(String(e.message).includes('one_exclusive'))throw conflict('device already has an exclusive session','DEVICE_BUSY');throw e}audit(db,{orgId:p.org,actorId:c.userId,action:'session.start',targetType:'device',targetId:deviceId,result:'allow',requestId:c.requestId});ok(res,{id},201);});
  router.get('/v1/orgs/:org/sessions',async(c,p,res)=>{requireOrg(db,c,p.org);assertCan(db,c,'session:view');ok(res,{sessions:db.prepare('SELECT * FROM sessions WHERE org_id=? ORDER BY started_at DESC').all(p.org)});});
  router.get('/v1/sessions/:id',async(c,p,res)=>{const s=db.prepare('SELECT * FROM sessions WHERE id=? AND org_id=?').get(p.id,c.orgId);if(!s)throw notFound();ok(res,s);});
  router.post('/v1/sessions/:id/stop',async(c,p,res)=>{const s=db.prepare('SELECT * FROM sessions WHERE id=? AND org_id=?').get(p.id,c.orgId);if(!s)throw notFound();if(s.user_id!==c.userId)assertCan(db,c,'session:terminate');db.prepare("UPDATE sessions SET state='ended',end_reason='user_stopped',ended_at=? WHERE id=?").run(nowIso(),p.id);ok(res,{stopped:true});});
  router.get('/v1/orgs/:org/audit',async(c,p,res)=>{requireOrg(db,c,p.org);assertCan(db,c,'audit:read');const [l,o]=pagination(c.query);ok(res,{events:db.prepare('SELECT * FROM audit_events WHERE org_id=? ORDER BY at DESC LIMIT ? OFFSET ?').all(p.org,l,o)});});
}
